// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqwBAoFTXNnSWQSEAoMTUVTU0FHRV9O",
            "T05FEAASEQoMQ19MT0dJTl9BVVRIEOkHEhEKDFNfTE9HSU5fQVVUSBDqBxIL",
            "CgZDX0pPSU4Q6wcSCwoGU19KT0lOEOwHEhEKDENfQVVUSF9UT0tFThDRDxIU",
            "Cg9DX0NSRUFURV9QTEFZRVIQ0g8SEQoMQ19FTlRFUl9HQU1FENMPEhUKEENf",
            "TE9BRF9DT01QTEVURUQQ1A8SCwoGQ19NT1ZFENUPEg0KCENfQVRUQUNLENYP",
            "Eg0KCENfUkVWSVZFENcPEgsKBkNfUVVJVBDYDxIVChBTX0dBTUVfQ09OTkVD",
            "VEVEELUQEhIKDVNfUExBWUVSX0xJU1QQthASFAoPU19DUkVBVEVfUExBWUVS",
            "ELcQEhEKDFNfRU5URVJfR0FNRRC4EBIMCgdTX1NQQVdOELkQEg4KCVNfREVT",
            "UEFXThC6EBILCgZTX01PVkUQuxASDQoIU19BVFRBQ0sQvBASCgoFU19ESUUQ",
            "vRASEAoLU19DSEFOR0VfSFAQvhASEQoMU19DSEFOR0VfRVhQEL8QEhIKDVNf",
            "Q0hBTkdFX1NUQVQQwBASEwoOU19DSEFOR0VfU1RBVEUQwRASEwoOU19DSEFO",
            "R0VfTEVWRUwQwhASDQoIU19SRVZJVkUQwxASEQoMQ19DSEFUX0xPR0lOELkX",
            "EhEKDFNfQ0hBVF9MT0dJThC6FxILCgZDX0NIQVQQuxcSCwoGU19DSEFUELwX",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("MESSAGE_NONE")] MessageNone = 0,
    [pbr::OriginalName("C_LOGIN_AUTH")] CLoginAuth = 1001,
    [pbr::OriginalName("S_LOGIN_AUTH")] SLoginAuth = 1002,
    [pbr::OriginalName("C_JOIN")] CJoin = 1003,
    [pbr::OriginalName("S_JOIN")] SJoin = 1004,
    [pbr::OriginalName("C_AUTH_TOKEN")] CAuthToken = 2001,
    [pbr::OriginalName("C_CREATE_PLAYER")] CCreatePlayer = 2002,
    [pbr::OriginalName("C_ENTER_GAME")] CEnterGame = 2003,
    [pbr::OriginalName("C_LOAD_COMPLETED")] CLoadCompleted = 2004,
    [pbr::OriginalName("C_MOVE")] CMove = 2005,
    [pbr::OriginalName("C_ATTACK")] CAttack = 2006,
    [pbr::OriginalName("C_REVIVE")] CRevive = 2007,
    [pbr::OriginalName("C_QUIT")] CQuit = 2008,
    [pbr::OriginalName("S_GAME_CONNECTED")] SGameConnected = 2101,
    [pbr::OriginalName("S_PLAYER_LIST")] SPlayerList = 2102,
    [pbr::OriginalName("S_CREATE_PLAYER")] SCreatePlayer = 2103,
    [pbr::OriginalName("S_ENTER_GAME")] SEnterGame = 2104,
    [pbr::OriginalName("S_SPAWN")] SSpawn = 2105,
    [pbr::OriginalName("S_DESPAWN")] SDespawn = 2106,
    [pbr::OriginalName("S_MOVE")] SMove = 2107,
    [pbr::OriginalName("S_ATTACK")] SAttack = 2108,
    [pbr::OriginalName("S_DIE")] SDie = 2109,
    [pbr::OriginalName("S_CHANGE_HP")] SChangeHp = 2110,
    [pbr::OriginalName("S_CHANGE_EXP")] SChangeExp = 2111,
    [pbr::OriginalName("S_CHANGE_STAT")] SChangeStat = 2112,
    [pbr::OriginalName("S_CHANGE_STATE")] SChangeState = 2113,
    [pbr::OriginalName("S_CHANGE_LEVEL")] SChangeLevel = 2114,
    [pbr::OriginalName("S_REVIVE")] SRevive = 2115,
    [pbr::OriginalName("C_CHAT_LOGIN")] CChatLogin = 3001,
    [pbr::OriginalName("S_CHAT_LOGIN")] SChatLogin = 3002,
    [pbr::OriginalName("C_CHAT")] CChat = 3003,
    [pbr::OriginalName("S_CHAT")] SChat = 3004,
  }

  #endregion

}

#endregion Designer generated code
