// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GatePacket.proto
// Protobuf C++ Version: 6.33.4

#ifndef GatePacket_2eproto_2epb_2eh
#define GatePacket_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_GatePacket_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_GatePacket_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_GatePacket_2eproto;
}  // extern "C"
namespace Protocol {
enum GateMsgId : int;
extern const uint32_t GateMsgId_internal_data_[];
class CQEnter;
struct CQEnterDefaultTypeInternal;
extern CQEnterDefaultTypeInternal _CQEnter_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CQEnter_class_data_;
class CQLeave;
struct CQLeaveDefaultTypeInternal;
extern CQLeaveDefaultTypeInternal _CQLeave_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CQLeave_class_data_;
class SQAdmitted;
struct SQAdmittedDefaultTypeInternal;
extern SQAdmittedDefaultTypeInternal _SQAdmitted_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SQAdmitted_class_data_;
class SQEnter;
struct SQEnterDefaultTypeInternal;
extern SQEnterDefaultTypeInternal _SQEnter_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SQEnter_class_data_;
class SQStatus;
struct SQStatusDefaultTypeInternal;
extern SQStatusDefaultTypeInternal _SQStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SQStatus_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Protocol::GateMsgId_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::GateMsgId>;
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum GateMsgId : int {
  G_NONE = 0,
  C_Q_ENTER = 1,
  S_Q_ENTER = 2,
  S_Q_STATUS = 3,
  S_Q_ADMITTED = 4,
  C_Q_LEAVE = 5,
  GateMsgId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GateMsgId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GateMsgId_internal_data_[];
inline constexpr GateMsgId GateMsgId_MIN =
    static_cast<GateMsgId>(0);
inline constexpr GateMsgId GateMsgId_MAX =
    static_cast<GateMsgId>(5);
inline bool GateMsgId_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int GateMsgId_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GateMsgId_descriptor();
template <typename T>
const ::std::string& GateMsgId_Name(T value) {
  static_assert(::std::is_same<T, GateMsgId>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GateMsgId_Name().");
  return GateMsgId_Name(static_cast<GateMsgId>(value));
}
template <>
inline const ::std::string& GateMsgId_Name(GateMsgId value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GateMsgId_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool GateMsgId_Parse(
    ::absl::string_view name, GateMsgId* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GateMsgId>(GateMsgId_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SQStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SQStatus) */ {
 public:
  inline SQStatus() : SQStatus(nullptr) {}
  ~SQStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SQStatus* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SQStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SQStatus(::google::protobuf::internal::ConstantInitialized);

  inline SQStatus(const SQStatus& from) : SQStatus(nullptr, from) {}
  inline SQStatus(SQStatus&& from) noexcept
      : SQStatus(nullptr, ::std::move(from)) {}
  inline SQStatus& operator=(const SQStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SQStatus& operator=(SQStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SQStatus& default_instance() {
    return *reinterpret_cast<const SQStatus*>(
        &_SQStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SQStatus& a, SQStatus& b) { a.Swap(&b); }
  inline void Swap(SQStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SQStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SQStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SQStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SQStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SQStatus& from) { SQStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SQStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SQStatus"; }

  explicit SQStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SQStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SQStatus& from);
  SQStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SQStatus&& from) noexcept
      : SQStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 1,
    kTotalFieldNumber = 2,
    kEtaSecFieldNumber = 3,
  };
  // int32 position = 1;
  void clear_position() ;
  ::int32_t position() const;
  void set_position(::int32_t value);

  private:
  ::int32_t _internal_position() const;
  void _internal_set_position(::int32_t value);

  public:
  // int32 total = 2;
  void clear_total() ;
  ::int32_t total() const;
  void set_total(::int32_t value);

  private:
  ::int32_t _internal_total() const;
  void _internal_set_total(::int32_t value);

  public:
  // int32 eta_sec = 3;
  void clear_eta_sec() ;
  ::int32_t eta_sec() const;
  void set_eta_sec(::int32_t value);

  private:
  ::int32_t _internal_eta_sec() const;
  void _internal_set_eta_sec(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SQStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SQStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t position_;
    ::int32_t total_;
    ::int32_t eta_sec_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GatePacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SQStatus_class_data_;
// -------------------------------------------------------------------

class SQEnter final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SQEnter) */ {
 public:
  inline SQEnter() : SQEnter(nullptr) {}
  ~SQEnter() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SQEnter* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SQEnter));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SQEnter(::google::protobuf::internal::ConstantInitialized);

  inline SQEnter(const SQEnter& from) : SQEnter(nullptr, from) {}
  inline SQEnter(SQEnter&& from) noexcept
      : SQEnter(nullptr, ::std::move(from)) {}
  inline SQEnter& operator=(const SQEnter& from) {
    CopyFrom(from);
    return *this;
  }
  inline SQEnter& operator=(SQEnter&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SQEnter& default_instance() {
    return *reinterpret_cast<const SQEnter*>(
        &_SQEnter_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SQEnter& a, SQEnter& b) { a.Swap(&b); }
  inline void Swap(SQEnter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SQEnter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SQEnter* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SQEnter>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SQEnter& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SQEnter& from) { SQEnter::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SQEnter* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SQEnter"; }

  explicit SQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SQEnter& from);
  SQEnter(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SQEnter&& from) noexcept
      : SQEnter(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string reason = 2;
  void clear_reason() ;
  const ::std::string& reason() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_reason(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_reason();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_reason();
  void set_allocated_reason(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_reason() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_reason();

  public:
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SQEnter)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SQEnter& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr reason_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GatePacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SQEnter_class_data_;
// -------------------------------------------------------------------

class SQAdmitted final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SQAdmitted) */ {
 public:
  inline SQAdmitted() : SQAdmitted(nullptr) {}
  ~SQAdmitted() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SQAdmitted* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SQAdmitted));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SQAdmitted(::google::protobuf::internal::ConstantInitialized);

  inline SQAdmitted(const SQAdmitted& from) : SQAdmitted(nullptr, from) {}
  inline SQAdmitted(SQAdmitted&& from) noexcept
      : SQAdmitted(nullptr, ::std::move(from)) {}
  inline SQAdmitted& operator=(const SQAdmitted& from) {
    CopyFrom(from);
    return *this;
  }
  inline SQAdmitted& operator=(SQAdmitted&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SQAdmitted& default_instance() {
    return *reinterpret_cast<const SQAdmitted*>(
        &_SQAdmitted_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SQAdmitted& a, SQAdmitted& b) { a.Swap(&b); }
  inline void Swap(SQAdmitted* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SQAdmitted* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SQAdmitted* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SQAdmitted>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SQAdmitted& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SQAdmitted& from) { SQAdmitted::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SQAdmitted* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SQAdmitted"; }

  explicit SQAdmitted(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SQAdmitted(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SQAdmitted& from);
  SQAdmitted(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SQAdmitted&& from) noexcept
      : SQAdmitted(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAuthTokenFieldNumber = 1,
    kGameIpFieldNumber = 2,
    kGamePortFieldNumber = 3,
  };
  // string auth_token = 1;
  void clear_auth_token() ;
  const ::std::string& auth_token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_auth_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_auth_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_auth_token();
  void set_allocated_auth_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_auth_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_auth_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_auth_token();

  public:
  // string game_ip = 2;
  void clear_game_ip() ;
  const ::std::string& game_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_game_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_game_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_game_ip();
  void set_allocated_game_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_game_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_game_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_game_ip();

  public:
  // int32 game_port = 3;
  void clear_game_port() ;
  ::int32_t game_port() const;
  void set_game_port(::int32_t value);

  private:
  ::int32_t _internal_game_port() const;
  void _internal_set_game_port(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SQAdmitted)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 45,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SQAdmitted& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr auth_token_;
    ::google::protobuf::internal::ArenaStringPtr game_ip_;
    ::int32_t game_port_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GatePacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SQAdmitted_class_data_;
// -------------------------------------------------------------------

class CQLeave final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.CQLeave) */ {
 public:
  inline CQLeave() : CQLeave(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CQLeave* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CQLeave));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CQLeave(::google::protobuf::internal::ConstantInitialized);

  inline CQLeave(const CQLeave& from) : CQLeave(nullptr, from) {}
  inline CQLeave(CQLeave&& from) noexcept
      : CQLeave(nullptr, ::std::move(from)) {}
  inline CQLeave& operator=(const CQLeave& from) {
    CopyFrom(from);
    return *this;
  }
  inline CQLeave& operator=(CQLeave&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CQLeave& default_instance() {
    return *reinterpret_cast<const CQLeave*>(
        &_CQLeave_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CQLeave& a, CQLeave& b) { a.Swap(&b); }
  inline void Swap(CQLeave* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CQLeave* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CQLeave* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<CQLeave>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const CQLeave& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const CQLeave& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.CQLeave"; }

  explicit CQLeave(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CQLeave(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CQLeave& from);
  CQLeave(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CQLeave&& from) noexcept
      : CQLeave(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.CQLeave)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_GatePacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CQLeave_class_data_;
// -------------------------------------------------------------------

class CQEnter final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.CQEnter) */ {
 public:
  inline CQEnter() : CQEnter(nullptr) {}
  ~CQEnter() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CQEnter* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CQEnter));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CQEnter(::google::protobuf::internal::ConstantInitialized);

  inline CQEnter(const CQEnter& from) : CQEnter(nullptr, from) {}
  inline CQEnter(CQEnter&& from) noexcept
      : CQEnter(nullptr, ::std::move(from)) {}
  inline CQEnter& operator=(const CQEnter& from) {
    CopyFrom(from);
    return *this;
  }
  inline CQEnter& operator=(CQEnter&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CQEnter& default_instance() {
    return *reinterpret_cast<const CQEnter*>(
        &_CQEnter_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CQEnter& a, CQEnter& b) { a.Swap(&b); }
  inline void Swap(CQEnter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CQEnter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CQEnter* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CQEnter>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CQEnter& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CQEnter& from) { CQEnter::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CQEnter* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.CQEnter"; }

  explicit CQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CQEnter& from);
  CQEnter(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CQEnter&& from) noexcept
      : CQEnter(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueueTokenFieldNumber = 1,
    kServerIdFieldNumber = 2,
  };
  // string queue_token = 1;
  void clear_queue_token() ;
  const ::std::string& queue_token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_queue_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_queue_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_queue_token();
  void set_allocated_queue_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_queue_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_queue_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_queue_token();

  public:
  // int32 server_id = 2;
  void clear_server_id() ;
  ::int32_t server_id() const;
  void set_server_id(::int32_t value);

  private:
  ::int32_t _internal_server_id() const;
  void _internal_set_server_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.CQEnter)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CQEnter& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr queue_token_;
    ::int32_t server_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GatePacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CQEnter_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CQEnter

// string queue_token = 1;
inline void CQEnter::clear_queue_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.queue_token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CQEnter::queue_token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.CQEnter.queue_token)
  return _internal_queue_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CQEnter::set_queue_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.queue_token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.CQEnter.queue_token)
}
inline ::std::string* PROTOBUF_NONNULL CQEnter::mutable_queue_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_queue_token();
  // @@protoc_insertion_point(field_mutable:Protocol.CQEnter.queue_token)
  return _s;
}
inline const ::std::string& CQEnter::_internal_queue_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.queue_token_.Get();
}
inline void CQEnter::_internal_set_queue_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.queue_token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CQEnter::_internal_mutable_queue_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.queue_token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CQEnter::release_queue_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.CQEnter.queue_token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.queue_token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.queue_token_.Set("", GetArena());
  }
  return released;
}
inline void CQEnter::set_allocated_queue_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.queue_token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.queue_token_.IsDefault()) {
    _impl_.queue_token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.CQEnter.queue_token)
}

// int32 server_id = 2;
inline void CQEnter::clear_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t CQEnter::server_id() const {
  // @@protoc_insertion_point(field_get:Protocol.CQEnter.server_id)
  return _internal_server_id();
}
inline void CQEnter::set_server_id(::int32_t value) {
  _internal_set_server_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.CQEnter.server_id)
}
inline ::int32_t CQEnter::_internal_server_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_id_;
}
inline void CQEnter::_internal_set_server_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_id_ = value;
}

// -------------------------------------------------------------------

// SQEnter

// bool success = 1;
inline void SQEnter::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool SQEnter::success() const {
  // @@protoc_insertion_point(field_get:Protocol.SQEnter.success)
  return _internal_success();
}
inline void SQEnter::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.SQEnter.success)
}
inline bool SQEnter::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void SQEnter::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string reason = 2;
inline void SQEnter::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SQEnter::reason() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SQEnter.reason)
  return _internal_reason();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SQEnter::set_reason(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.reason_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.SQEnter.reason)
}
inline ::std::string* PROTOBUF_NONNULL SQEnter::mutable_reason()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.SQEnter.reason)
  return _s;
}
inline const ::std::string& SQEnter::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_.Get();
}
inline void SQEnter::_internal_set_reason(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SQEnter::_internal_mutable_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.reason_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SQEnter::release_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SQEnter.reason)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.reason_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.reason_.Set("", GetArena());
  }
  return released;
}
inline void SQEnter::set_allocated_reason(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.reason_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.SQEnter.reason)
}

// -------------------------------------------------------------------

// SQStatus

// int32 position = 1;
inline void SQStatus::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t SQStatus::position() const {
  // @@protoc_insertion_point(field_get:Protocol.SQStatus.position)
  return _internal_position();
}
inline void SQStatus::set_position(::int32_t value) {
  _internal_set_position(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.SQStatus.position)
}
inline ::int32_t SQStatus::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline void SQStatus::_internal_set_position(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = value;
}

// int32 total = 2;
inline void SQStatus::clear_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SQStatus::total() const {
  // @@protoc_insertion_point(field_get:Protocol.SQStatus.total)
  return _internal_total();
}
inline void SQStatus::set_total(::int32_t value) {
  _internal_set_total(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.SQStatus.total)
}
inline ::int32_t SQStatus::_internal_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_;
}
inline void SQStatus::_internal_set_total(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = value;
}

// int32 eta_sec = 3;
inline void SQStatus::clear_eta_sec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eta_sec_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SQStatus::eta_sec() const {
  // @@protoc_insertion_point(field_get:Protocol.SQStatus.eta_sec)
  return _internal_eta_sec();
}
inline void SQStatus::set_eta_sec(::int32_t value) {
  _internal_set_eta_sec(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.SQStatus.eta_sec)
}
inline ::int32_t SQStatus::_internal_eta_sec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eta_sec_;
}
inline void SQStatus::_internal_set_eta_sec(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eta_sec_ = value;
}

// -------------------------------------------------------------------

// SQAdmitted

// string auth_token = 1;
inline void SQAdmitted::clear_auth_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SQAdmitted::auth_token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SQAdmitted.auth_token)
  return _internal_auth_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SQAdmitted::set_auth_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.auth_token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.SQAdmitted.auth_token)
}
inline ::std::string* PROTOBUF_NONNULL SQAdmitted::mutable_auth_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_auth_token();
  // @@protoc_insertion_point(field_mutable:Protocol.SQAdmitted.auth_token)
  return _s;
}
inline const ::std::string& SQAdmitted::_internal_auth_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.auth_token_.Get();
}
inline void SQAdmitted::_internal_set_auth_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.auth_token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SQAdmitted::_internal_mutable_auth_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.auth_token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SQAdmitted::release_auth_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SQAdmitted.auth_token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.auth_token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.auth_token_.Set("", GetArena());
  }
  return released;
}
inline void SQAdmitted::set_allocated_auth_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.auth_token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.auth_token_.IsDefault()) {
    _impl_.auth_token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.SQAdmitted.auth_token)
}

// string game_ip = 2;
inline void SQAdmitted::clear_game_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& SQAdmitted::game_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SQAdmitted.game_ip)
  return _internal_game_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SQAdmitted::set_game_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.game_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.SQAdmitted.game_ip)
}
inline ::std::string* PROTOBUF_NONNULL SQAdmitted::mutable_game_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_game_ip();
  // @@protoc_insertion_point(field_mutable:Protocol.SQAdmitted.game_ip)
  return _s;
}
inline const ::std::string& SQAdmitted::_internal_game_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_ip_.Get();
}
inline void SQAdmitted::_internal_set_game_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SQAdmitted::_internal_mutable_game_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.game_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SQAdmitted::release_game_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SQAdmitted.game_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.game_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.game_ip_.Set("", GetArena());
  }
  return released;
}
inline void SQAdmitted::set_allocated_game_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.game_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.game_ip_.IsDefault()) {
    _impl_.game_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.SQAdmitted.game_ip)
}

// int32 game_port = 3;
inline void SQAdmitted::clear_game_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_port_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SQAdmitted::game_port() const {
  // @@protoc_insertion_point(field_get:Protocol.SQAdmitted.game_port)
  return _internal_game_port();
}
inline void SQAdmitted::set_game_port(::int32_t value) {
  _internal_set_game_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.SQAdmitted.game_port)
}
inline ::int32_t SQAdmitted::_internal_game_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_port_;
}
inline void SQAdmitted::_internal_set_game_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_port_ = value;
}

// -------------------------------------------------------------------

// CQLeave

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::GateMsgId> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::GateMsgId>() {
  return ::Protocol::GateMsgId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GatePacket_2eproto_2epb_2eh
