// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GatePacket.proto
// Protobuf C++ Version: 6.33.4

#include "GatePacket.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr SQStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{0},
        total_{0},
        eta_sec_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SQStatus::SQStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SQStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SQStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SQStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SQStatusDefaultTypeInternal() {}
  union {
    SQStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SQStatusDefaultTypeInternal _SQStatus_default_instance_;

inline constexpr SQEnter::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SQEnter::SQEnter(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SQEnter_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SQEnterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SQEnterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SQEnterDefaultTypeInternal() {}
  union {
    SQEnter _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SQEnterDefaultTypeInternal _SQEnter_default_instance_;

inline constexpr SQAdmitted::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        auth_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        game_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        game_port_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SQAdmitted::SQAdmitted(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SQAdmitted_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SQAdmittedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SQAdmittedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SQAdmittedDefaultTypeInternal() {}
  union {
    SQAdmitted _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SQAdmittedDefaultTypeInternal _SQAdmitted_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CQLeave::CQLeave(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(CQLeave_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CQLeaveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CQLeaveDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CQLeaveDefaultTypeInternal() {}
  union {
    CQLeave _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CQLeaveDefaultTypeInternal _CQLeave_default_instance_;

inline constexpr CQEnter::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        queue_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        server_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CQEnter::CQEnter(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CQEnter_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CQEnterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CQEnterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CQEnterDefaultTypeInternal() {}
  union {
    CQEnter _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CQEnterDefaultTypeInternal _CQEnter_default_instance_;
}  // namespace Protocol
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_GatePacket_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_GatePacket_2eproto = nullptr;
const ::uint32_t
    TableStruct_GatePacket_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::CQEnter, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::CQEnter, _impl_.queue_token_),
        PROTOBUF_FIELD_OFFSET(::Protocol::CQEnter, _impl_.server_id_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::SQEnter, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::SQEnter, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SQEnter, _impl_.reason_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::SQStatus, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::SQStatus, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SQStatus, _impl_.total_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SQStatus, _impl_.eta_sec_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::SQAdmitted, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::SQAdmitted, _impl_.auth_token_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SQAdmitted, _impl_.game_ip_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SQAdmitted, _impl_.game_port_),
        0,
        1,
        2,
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Protocol::CQEnter)},
        {7, sizeof(::Protocol::SQEnter)},
        {14, sizeof(::Protocol::SQStatus)},
        {23, sizeof(::Protocol::SQAdmitted)},
        {32, sizeof(::Protocol::CQLeave)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Protocol::_CQEnter_default_instance_._instance,
    &::Protocol::_SQEnter_default_instance_._instance,
    &::Protocol::_SQStatus_default_instance_._instance,
    &::Protocol::_SQAdmitted_default_instance_._instance,
    &::Protocol::_CQLeave_default_instance_._instance,
};
const char descriptor_table_protodef_GatePacket_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020GatePacket.proto\022\010Protocol\"1\n\007CQEnter\022"
    "\023\n\013queue_token\030\001 \001(\t\022\021\n\tserver_id\030\002 \001(\005\""
    "*\n\007SQEnter\022\017\n\007success\030\001 \001(\010\022\016\n\006reason\030\002 "
    "\001(\t\"<\n\010SQStatus\022\020\n\010position\030\001 \001(\005\022\r\n\005tot"
    "al\030\002 \001(\005\022\017\n\007eta_sec\030\003 \001(\005\"D\n\nSQAdmitted\022"
    "\022\n\nauth_token\030\001 \001(\t\022\017\n\007game_ip\030\002 \001(\t\022\021\n\t"
    "game_port\030\003 \001(\005\"\t\n\007CQLeave*f\n\tGateMsgId\022"
    "\n\n\006G_NONE\020\000\022\r\n\tC_Q_ENTER\020\001\022\r\n\tS_Q_ENTER\020"
    "\002\022\016\n\nS_Q_STATUS\020\003\022\020\n\014S_Q_ADMITTED\020\004\022\r\n\tC"
    "_Q_LEAVE\020\005b\006proto3"
};
static ::absl::once_flag descriptor_table_GatePacket_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_GatePacket_2eproto = {
    false,
    false,
    378,
    descriptor_table_protodef_GatePacket_2eproto,
    "GatePacket.proto",
    &descriptor_table_GatePacket_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_GatePacket_2eproto::offsets,
    file_level_enum_descriptors_GatePacket_2eproto,
    file_level_service_descriptors_GatePacket_2eproto,
};
namespace Protocol {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GateMsgId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_GatePacket_2eproto);
  return file_level_enum_descriptors_GatePacket_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GateMsgId_internal_data_[] = {
    393216u, 0u, };
// ===================================================================

class CQEnter::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CQEnter>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CQEnter, _impl_._has_bits_);
};

CQEnter::CQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CQEnter_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CQEnter)
}
PROTOBUF_NDEBUG_INLINE CQEnter::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol::CQEnter& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        queue_token_(arena, from.queue_token_) {}

CQEnter::CQEnter(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CQEnter& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CQEnter_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CQEnter* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.server_id_ = from._impl_.server_id_;

  // @@protoc_insertion_point(copy_constructor:Protocol.CQEnter)
}
PROTOBUF_NDEBUG_INLINE CQEnter::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        queue_token_(arena) {}

inline void CQEnter::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_id_ = {};
}
CQEnter::~CQEnter() {
  // @@protoc_insertion_point(destructor:Protocol.CQEnter)
  SharedDtor(*this);
}
inline void CQEnter::SharedDtor(MessageLite& self) {
  CQEnter& this_ = static_cast<CQEnter&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.queue_token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CQEnter::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CQEnter(arena);
}
constexpr auto CQEnter::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CQEnter),
                                            alignof(CQEnter));
}
constexpr auto CQEnter::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CQEnter_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CQEnter::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CQEnter>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CQEnter::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CQEnter>(), &CQEnter::ByteSizeLong,
              &CQEnter::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CQEnter, _impl_._cached_size_),
          false,
      },
      &CQEnter::kDescriptorMethods,
      &descriptor_table_GatePacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CQEnter_class_data_ =
        CQEnter::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CQEnter::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CQEnter_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CQEnter_class_data_.tc_table);
  return CQEnter_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2>
CQEnter::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CQEnter, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CQEnter_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CQEnter>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 server_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CQEnter, _impl_.server_id_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CQEnter, _impl_.server_id_)}},
    // string queue_token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CQEnter, _impl_.queue_token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string queue_token = 1;
    {PROTOBUF_FIELD_OFFSET(CQEnter, _impl_.queue_token_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 server_id = 2;
    {PROTOBUF_FIELD_OFFSET(CQEnter, _impl_.server_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\20\13\0\0\0\0\0\0"
    "Protocol.CQEnter"
    "queue_token"
  }},
};
PROTOBUF_NOINLINE void CQEnter::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CQEnter)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.queue_token_.ClearNonDefaultToEmpty();
  }
  _impl_.server_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CQEnter::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CQEnter& this_ = static_cast<const CQEnter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CQEnter::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CQEnter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CQEnter)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string queue_token = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_queue_token().empty()) {
      const ::std::string& _s = this_._internal_queue_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CQEnter.queue_token");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 server_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_server_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_server_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CQEnter)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CQEnter::ByteSizeLong(const MessageLite& base) {
  const CQEnter& this_ = static_cast<const CQEnter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CQEnter::ByteSizeLong() const {
  const CQEnter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.CQEnter)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string queue_token = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_queue_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_queue_token());
      }
    }
    // int32 server_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_server_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_server_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CQEnter::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CQEnter*>(&to_msg);
  auto& from = static_cast<const CQEnter&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CQEnter)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_queue_token().empty()) {
        _this->_internal_set_queue_token(from._internal_queue_token());
      } else {
        if (_this->_impl_.queue_token_.IsDefault()) {
          _this->_internal_set_queue_token("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_server_id() != 0) {
        _this->_impl_.server_id_ = from._impl_.server_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CQEnter::CopyFrom(const CQEnter& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CQEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CQEnter::InternalSwap(CQEnter* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.queue_token_, &other->_impl_.queue_token_, arena);
  swap(_impl_.server_id_, other->_impl_.server_id_);
}

::google::protobuf::Metadata CQEnter::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SQEnter::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SQEnter>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SQEnter, _impl_._has_bits_);
};

SQEnter::SQEnter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQEnter_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SQEnter)
}
PROTOBUF_NDEBUG_INLINE SQEnter::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol::SQEnter& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

SQEnter::SQEnter(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SQEnter& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQEnter_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SQEnter* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:Protocol.SQEnter)
}
PROTOBUF_NDEBUG_INLINE SQEnter::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void SQEnter::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
SQEnter::~SQEnter() {
  // @@protoc_insertion_point(destructor:Protocol.SQEnter)
  SharedDtor(*this);
}
inline void SQEnter::SharedDtor(MessageLite& self) {
  SQEnter& this_ = static_cast<SQEnter&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SQEnter::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SQEnter(arena);
}
constexpr auto SQEnter::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SQEnter),
                                            alignof(SQEnter));
}
constexpr auto SQEnter::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SQEnter_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SQEnter::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SQEnter>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SQEnter::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SQEnter>(), &SQEnter::ByteSizeLong,
              &SQEnter::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SQEnter, _impl_._cached_size_),
          false,
      },
      &SQEnter::kDescriptorMethods,
      &descriptor_table_GatePacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SQEnter_class_data_ =
        SQEnter::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SQEnter::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SQEnter_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SQEnter_class_data_.tc_table);
  return SQEnter_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2>
SQEnter::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SQEnter, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SQEnter_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SQEnter>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string reason = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SQEnter, _impl_.reason_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SQEnter, _impl_.success_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SQEnter, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(SQEnter, _impl_.success_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string reason = 2;
    {PROTOBUF_FIELD_OFFSET(SQEnter, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\6\0\0\0\0\0"
    "Protocol.SQEnter"
    "reason"
  }},
};
PROTOBUF_NOINLINE void SQEnter::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SQEnter)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.reason_.ClearNonDefaultToEmpty();
  }
  _impl_.success_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SQEnter::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SQEnter& this_ = static_cast<const SQEnter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SQEnter::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SQEnter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SQEnter)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool success = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_success(), target);
    }
  }

  // string reason = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_reason().empty()) {
      const ::std::string& _s = this_._internal_reason();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SQEnter.reason");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SQEnter)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SQEnter::ByteSizeLong(const MessageLite& base) {
  const SQEnter& this_ = static_cast<const SQEnter&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SQEnter::ByteSizeLong() const {
  const SQEnter& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.SQEnter)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string reason = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_reason().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_reason());
      }
    }
    // bool success = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SQEnter::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SQEnter*>(&to_msg);
  auto& from = static_cast<const SQEnter&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SQEnter)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_reason().empty()) {
        _this->_internal_set_reason(from._internal_reason());
      } else {
        if (_this->_impl_.reason_.IsDefault()) {
          _this->_internal_set_reason("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_success() != 0) {
        _this->_impl_.success_ = from._impl_.success_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SQEnter::CopyFrom(const SQEnter& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SQEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SQEnter::InternalSwap(SQEnter* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reason_, &other->_impl_.reason_, arena);
  swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata SQEnter::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SQStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SQStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SQStatus, _impl_._has_bits_);
};

SQStatus::SQStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SQStatus)
}
SQStatus::SQStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SQStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SQStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SQStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, position_),
           0,
           offsetof(Impl_, eta_sec_) -
               offsetof(Impl_, position_) +
               sizeof(Impl_::eta_sec_));
}
SQStatus::~SQStatus() {
  // @@protoc_insertion_point(destructor:Protocol.SQStatus)
  SharedDtor(*this);
}
inline void SQStatus::SharedDtor(MessageLite& self) {
  SQStatus& this_ = static_cast<SQStatus&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SQStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SQStatus(arena);
}
constexpr auto SQStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SQStatus),
                                            alignof(SQStatus));
}
constexpr auto SQStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SQStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SQStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SQStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SQStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SQStatus>(), &SQStatus::ByteSizeLong,
              &SQStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SQStatus, _impl_._cached_size_),
          false,
      },
      &SQStatus::kDescriptorMethods,
      &descriptor_table_GatePacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SQStatus_class_data_ =
        SQStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SQStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SQStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SQStatus_class_data_.tc_table);
  return SQStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
SQStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SQStatus, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SQStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SQStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 position = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SQStatus, _impl_.position_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.position_)}},
    // int32 total = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SQStatus, _impl_.total_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.total_)}},
    // int32 eta_sec = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SQStatus, _impl_.eta_sec_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.eta_sec_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 position = 1;
    {PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.position_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 total = 2;
    {PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.total_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 eta_sec = 3;
    {PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.eta_sec_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SQStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SQStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.position_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.eta_sec_) -
        reinterpret_cast<char*>(&_impl_.position_)) + sizeof(_impl_.eta_sec_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SQStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SQStatus& this_ = static_cast<const SQStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SQStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SQStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SQStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 position = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_position() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_position(), target);
    }
  }

  // int32 total = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_total() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_total(), target);
    }
  }

  // int32 eta_sec = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_eta_sec() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_eta_sec(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SQStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SQStatus::ByteSizeLong(const MessageLite& base) {
  const SQStatus& this_ = static_cast<const SQStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SQStatus::ByteSizeLong() const {
  const SQStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.SQStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // int32 position = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_position() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_position());
      }
    }
    // int32 total = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_total() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_total());
      }
    }
    // int32 eta_sec = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_eta_sec() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_eta_sec());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SQStatus::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SQStatus*>(&to_msg);
  auto& from = static_cast<const SQStatus&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SQStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_position() != 0) {
        _this->_impl_.position_ = from._impl_.position_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_total() != 0) {
        _this->_impl_.total_ = from._impl_.total_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_eta_sec() != 0) {
        _this->_impl_.eta_sec_ = from._impl_.eta_sec_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SQStatus::CopyFrom(const SQStatus& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SQStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SQStatus::InternalSwap(SQStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.eta_sec_)
      + sizeof(SQStatus::_impl_.eta_sec_)
      - PROTOBUF_FIELD_OFFSET(SQStatus, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::google::protobuf::Metadata SQStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SQAdmitted::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SQAdmitted>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_._has_bits_);
};

SQAdmitted::SQAdmitted(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQAdmitted_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SQAdmitted)
}
PROTOBUF_NDEBUG_INLINE SQAdmitted::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol::SQAdmitted& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        auth_token_(arena, from.auth_token_),
        game_ip_(arena, from.game_ip_) {}

SQAdmitted::SQAdmitted(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SQAdmitted& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SQAdmitted_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SQAdmitted* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.game_port_ = from._impl_.game_port_;

  // @@protoc_insertion_point(copy_constructor:Protocol.SQAdmitted)
}
PROTOBUF_NDEBUG_INLINE SQAdmitted::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        auth_token_(arena),
        game_ip_(arena) {}

inline void SQAdmitted::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.game_port_ = {};
}
SQAdmitted::~SQAdmitted() {
  // @@protoc_insertion_point(destructor:Protocol.SQAdmitted)
  SharedDtor(*this);
}
inline void SQAdmitted::SharedDtor(MessageLite& self) {
  SQAdmitted& this_ = static_cast<SQAdmitted&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.auth_token_.Destroy();
  this_._impl_.game_ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SQAdmitted::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SQAdmitted(arena);
}
constexpr auto SQAdmitted::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SQAdmitted),
                                            alignof(SQAdmitted));
}
constexpr auto SQAdmitted::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SQAdmitted_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SQAdmitted::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SQAdmitted>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SQAdmitted::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SQAdmitted>(), &SQAdmitted::ByteSizeLong,
              &SQAdmitted::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_._cached_size_),
          false,
      },
      &SQAdmitted::kDescriptorMethods,
      &descriptor_table_GatePacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SQAdmitted_class_data_ =
        SQAdmitted::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SQAdmitted::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SQAdmitted_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SQAdmitted_class_data_.tc_table);
  return SQAdmitted_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 45, 2>
SQAdmitted::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SQAdmitted_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SQAdmitted>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string auth_token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.auth_token_)}},
    // string game_ip = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.game_ip_)}},
    // int32 game_port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SQAdmitted, _impl_.game_port_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.game_port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string auth_token = 1;
    {PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.auth_token_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string game_ip = 2;
    {PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.game_ip_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 game_port = 3;
    {PROTOBUF_FIELD_OFFSET(SQAdmitted, _impl_.game_port_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\23\12\7\0\0\0\0\0"
    "Protocol.SQAdmitted"
    "auth_token"
    "game_ip"
  }},
};
PROTOBUF_NOINLINE void SQAdmitted::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SQAdmitted)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.auth_token_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.game_ip_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.game_port_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SQAdmitted::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SQAdmitted& this_ = static_cast<const SQAdmitted&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SQAdmitted::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SQAdmitted& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SQAdmitted)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string auth_token = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_auth_token().empty()) {
      const ::std::string& _s = this_._internal_auth_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SQAdmitted.auth_token");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string game_ip = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_game_ip().empty()) {
      const ::std::string& _s = this_._internal_game_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SQAdmitted.game_ip");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 game_port = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_game_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_game_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SQAdmitted)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SQAdmitted::ByteSizeLong(const MessageLite& base) {
  const SQAdmitted& this_ = static_cast<const SQAdmitted&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SQAdmitted::ByteSizeLong() const {
  const SQAdmitted& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.SQAdmitted)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string auth_token = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_auth_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_auth_token());
      }
    }
    // string game_ip = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_game_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_game_ip());
      }
    }
    // int32 game_port = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_game_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_game_port());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SQAdmitted::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SQAdmitted*>(&to_msg);
  auto& from = static_cast<const SQAdmitted&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SQAdmitted)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_auth_token().empty()) {
        _this->_internal_set_auth_token(from._internal_auth_token());
      } else {
        if (_this->_impl_.auth_token_.IsDefault()) {
          _this->_internal_set_auth_token("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_game_ip().empty()) {
        _this->_internal_set_game_ip(from._internal_game_ip());
      } else {
        if (_this->_impl_.game_ip_.IsDefault()) {
          _this->_internal_set_game_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_game_port() != 0) {
        _this->_impl_.game_port_ = from._impl_.game_port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SQAdmitted::CopyFrom(const SQAdmitted& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SQAdmitted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SQAdmitted::InternalSwap(SQAdmitted* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.auth_token_, &other->_impl_.auth_token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.game_ip_, &other->_impl_.game_ip_, arena);
  swap(_impl_.game_port_, other->_impl_.game_port_);
}

::google::protobuf::Metadata SQAdmitted::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CQLeave::_Internal {
 public:
};

CQLeave::CQLeave(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CQLeave_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.CQLeave)
}
CQLeave::CQLeave(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CQLeave& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CQLeave_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CQLeave* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.CQLeave)
}

inline void* PROTOBUF_NONNULL CQLeave::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CQLeave(arena);
}
constexpr auto CQLeave::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CQLeave),
                                            alignof(CQLeave));
}
constexpr auto CQLeave::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CQLeave_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CQLeave::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CQLeave>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CQLeave::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CQLeave>(), &CQLeave::ByteSizeLong,
              &CQLeave::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CQLeave, _impl_._cached_size_),
          false,
      },
      &CQLeave::kDescriptorMethods,
      &descriptor_table_GatePacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CQLeave_class_data_ =
        CQLeave::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CQLeave::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CQLeave_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CQLeave_class_data_.tc_table);
  return CQLeave_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
CQLeave::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CQLeave_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CQLeave>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata CQLeave::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_GatePacket_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
